### ISSUE TITLE
Exception occurs when run a elastic-sink

### ISSUE THREAD

**Issue by dujijun007** [Landoop/kafka-connect-tools#26]
java.lang.NoSuchMethodError: io.netty.util.internal.ObjectUtil.checkPositive(ILjava/lang/String;)I
	at io.netty.util.NettyRuntime$AvailableProcessorsHolder.setAvailableProcessors(NettyRuntime.java:44)
	at io.netty.util.NettyRuntime$AvailableProcessorsHolder.availableProcessors(NettyRuntime.java:70)
	at io.netty.util.NettyRuntime.availableProcessors(NettyRuntime.java:98)
	at org.elasticsearch.transport.netty4.Netty4Utils.setAvailableProcessors(Netty4Utils.java:83)
	at org.elasticsearch.transport.netty4.Netty4Transport.<init>(Netty4Transport.java:138)
	at org.elasticsearch.transport.Netty4Plugin.lambda$getTransports$0(Netty4Plugin.java:93)
	at org.elasticsearch.client.transport.TransportClient.buildTemplate(TransportClient.java:176)
	at org.elasticsearch.client.transport.TransportClient.<init>(TransportClient.java:268)
	at org.elasticsearch.transport.client.PreBuiltTransportClient.<init>(PreBuiltTransportClient.java:127)
	at org.elasticsearch.transport.client.PreBuiltTransportClient.<init>(PreBuiltTransportClient.java:113)
	at org.elasticsearch.transport.client.PreBuiltTransportClient.<init>(PreBuiltTransportClient.java:103)
	at com.sksamuel.elastic4s.TcpClientConstructors$class.transport(TcpClient.scala:104)
	at com.sksamuel.elastic4s.TcpClient$.transport(TcpClient.scala:112)
	at com.datamountaineer.streamreactor.connect.elastic5.KElasticClient$.getClient(KElasticClient.scala:47)
	at com.datamountaineer.streamreactor.connect.elastic5.ElasticWriter$.apply(ElasticWriter.scala:45)
	at com.datamountaineer.streamreactor.connect.elastic5.ElasticSinkTask.start(ElasticSinkTask.scala:44)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.initializeAndStart(WorkerSinkTask.java:232)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:145)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:146)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:190)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by andrewstevenson** [comment]
@dujijun007 You have to provide more information than a random stack trace. What version of the stream reactor? whats the configuration?

**Comment by andrewstevenson** [comment]
No reply so closing

**Comment by ebuildy** [comment]
In general this errors means you have 2 netty versions on the project.
