### ISSUE TITLE
Unable to validate sink properties

### ISSUE THREAD

**Issue by IDispose** [Landoop/kafka-connect-tools#29]
Per documentation I should be able to validate the sink properties via

`connect-cli validate < kudu_sink.properties`

However I get

`Error: Please specify the connector-name`

Tried

`connect-cli validate kudu-sink < kudu_sink.properties`

but that throws

```
java.lang.Exception:  Error: the Kafka Connect API returned status code 400
	at com.datamountaineer.connect.tools.RestKafkaConnectApi.non2xxException(RestKafkaConnectApi.scala:122)
	at com.datamountaineer.connect.tools.RestKafkaConnectApi.com$datamountaineer$connect$tools$RestKafkaConnectApi$$req(RestKafkaConnectApi.scala:139)
	at com.datamountaineer.connect.tools.RestKafkaConnectApi$$anonfun$connectorPluginsValidate$1.apply(RestKafkaConnectApi.scala:270)
	at com.datamountaineer.connect.tools.RestKafkaConnectApi$$anonfun$connectorPluginsValidate$1.apply(RestKafkaConnectApi.scala:270)
	at scala.util.Try$.apply(Try.scala:192)
	at com.datamountaineer.connect.tools.RestKafkaConnectApi.connectorPluginsValidate(RestKafkaConnectApi.scala:270)
	at com.datamountaineer.connect.tools.ExecuteCommand$.apply(Cli.scala:71)
	at com.datamountaineer.connect.tools.Cli$.main(Cli.scala:194)
	at com.datamountaineer.connect.tools.Cli.main(Cli.scala)

```

**Comment by andrewstevenson** [comment]
@IDispose I'll update the docs, it should be 

``connect-cli validate ConnectorClassName < kudu_sink.properties``

``connect-cli validate KuduSinkConnector < kudu_sink.properties``
